apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: production
spec:
  selector:
    app: build-max-frontend 
  ports:
    - name: http
      port: 80
      targetPort: 5173 
  type: LoadBalancer