name: deploy

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_NAME_TWO }}
          password: ${{ secrets.DOCKER_HUB_PSWD_TWO }}

      - name: Build and Push Frontend
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./client/my-app/Dockerfile
          push: true
          tags: soban11776/bm-frontend:latest

      - name: Build and Push Backend
        uses: docker/build-push-action@v5
        with:
          # Use the server folder as the build context
          context: ./server
          file: ./server/Dockerfile
          push: true
          tags: soban11776/bm-backend:latest
